#!/bin/sh

cd "/home/phahn/dev/cscope"

find ~/dev/pic_firmware -iname '*.[CH]' \
       -o -iname '*.cpp' \
       -o -iname '*.cc' \
       -o -iname '*.hpp' | sed 's/.*/"&"/' > "cscope.files"

find ~/dev/mp_vision/modules -iname '*.py' \
       -o -iname '*.java' \
       -o -iname '*.[CH]' \
       -o -iname '*.cpp' \
       -o -iname '*.cc' \
       -o -iname '*.hpp'  >> "cscope.files"
#       -o -type d \( -path "*AmbaRelease_21-2-evk" \) -prune \
#       -o -type d \( -path "*AmbaRelease_21-2-pure" \) -prune \
#       -o -type d \( -path "*AmbaRelease_21-2uc" \) -prune \
#       -o -type d \( -path "*20140603_fw_May_29_2014" \) -prune \
#       -o -type d \( -path "*20140422_new_src_SD_boot" \) -prune > "cscope.files"

#find ~/dev/linux-imx6 -iname '*.py' \
#       -o -iname '*.java' \
#       -o -iname '*.[CH]' \
#       -o -iname '*.cpp' \
#       -o -iname '*.cc' \
#       -o -iname '*.hpp' >> "cscope.files"

find ~/dev/mpv_build -iname '*.py' \
       -o -iname '*.java' \
       -o -iname '*.[CH]' \
       -o -iname '*.cpp' \
       -o -iname '*.cc' \
       -o -iname '*.hpp' >> "cscope.files"

#find ~/docker/eos-build-dev/ -iname '*.py' \
#       -o -iname '*.java' \
#       -o -iname '*.[CH]' \
#       -o -iname '*.cpp' \
#       -o -iname '*.cc' \
#       -o -iname '*.hpp' >> "cscope.files"

find ~/dev/zaya_app -iname '*.py' \
       -o -iname '*.java' \
       -o -iname '*.[CH]' \
       -o -iname '*.cpp' \
       -o -iname '*.cc' \
       -o -iname '*.hpp' \
       -o -type d \( -path "*modules" \) -prune \
       -o -type d \( -path "*thirdparty" \) -prune >> "cscope.files"

find ~/dev/zaya_mcu -iname '*.py' \
       -o -iname '*.java' \
       -o -iname '*.[CH]' \
       -o -iname '*.cpp' \
       -o -iname '*.cc' \
       -o -iname '*.hpp' >> "cscope.files"

# -b: just build
# -q: create inverted index
       cscope -b -q
cd -
